language: node_js
node_js:
- '0.10'
install:
- npm install -g bower
- npm install
- bower install
script:
- npm run travis
after_script:
- cat ./test/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
env:
  global:
  - secure: EzANlzV6ODIGivZvsQZUFj0bdjCr/YuEdAq1kmHKO5RLUuhfHJOpDRhQqybY/Sub5tUjRYz57wYlilM8Zqa+9LoltYz/e0NedjsEpH9AMXut9ibtFFtW2kEsWb2f1+fuuTSjyh9Xc6sYZ4FuNp1YlDXnq3msbbd1ZzyqKcvn5Gs=
  - secure: k81/PTyCCZfuScBI7kaxnIhRANtBURW/HtHIK47u2SpWprCt/ESjy345585NDRV1c95FnDF1F9Hz2vZ0wur9/m5aFCGOPSiGZUl4vUPPiB22+M3E8MvVAXvgL6yL5txq5ckYw3pMeTlS75+VXrtPrBIJ9wjjw6ka/ivX8vtnA2I=
